FROM quay.io/keycloak/keycloak:latest as builder
#ENV KC_HEALTH_ENABLED=true
ENV KC_FEATURES=token-exchange
ENV KC_METRICS_ENABLED=true
#ENV KC_HTTP_RELATIVE_PATH="/auth"
# Install custom providers
# Apple Social Identity Provider - https://github.com/klausbetz/apple-identity-provider-keycloak
ADD --chown=keycloak:keycloak https://github.com/klausbetz/apple-identity-provider-keycloak/releases/download/1.10.0/apple-identity-provider-1.10.0.jar /opt/keycloak/providers/apple-identity-provider-1.10.0.jar
# build optimized image
RUN /opt/keycloak/bin/kc.sh build 
#
FROM quay.io/keycloak/keycloak:latest as druid-builder
#ENV KC_HEALTH_ENABLED=true
ENV KC_FEATURES=token-exchange
ENV KC_METRICS_ENABLED=true
# Install custom providers
#COPY druid-social-identity-provider-1.0.3.jar /opt/keycloak/providers/druid-social-identity-provider-1.0.3.jar 
ADD --chown=keycloak:keycloak https://github.com/HiWay-Media/keycloak-identity-provider-druid/releases/download/1.0.0/druid-social-identity-provider-prod-1.1.0.jar /opt/keycloak/providers/druid-social-identity-provider-prod-1.1.0.jar 
# build optimized image
RUN /opt/keycloak/bin/kc.sh build 
#
#
FROM quay.io/keycloak/keycloak:latest
WORKDIR /opt/keycloak
COPY --from=builder /opt/keycloak/ /opt/keycloak/
COPY --from=druid-builder /opt/keycloak/ /opt/keycloak/
RUN /opt/keycloak/bin/kc.sh build 
#
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
#