FROM quay.io/keycloak/keycloak:22.0.1 as builder
#ENV KC_HEALTH_ENABLED=true
ENV KC_FEATURES=impersonation,admin-fine-grained-authz,token-exchange
ENV KC_METRICS_ENABLED=true
#ENV KC_HTTP_RELATIVE_PATH="/auth"
# Install custom providers
# Apple Social Identity Provider - https://github.com/klausbetz/apple-identity-provider-keycloak
ADD --chown=keycloak:keycloak https://github.com/klausbetz/apple-identity-provider-keycloak/releases/download/1.10.0/apple-identity-provider-1.10.0.jar /opt/keycloak/providers/apple-identity-provider-1.10.0.jar
# Druid Social Identity Provider
ADD --chown=keycloak:keycloak https://github.com/HiWay-Media/keycloak-identity-provider-druid/releases/download/v1.0.1/druid-social-identity-provider-dev-1.1.0.jar /opt/keycloak/providers/druid-social-identity-provider-dev-1.1.0.jar
# FITP Enricher
ADD --chown=keycloak:keycloak https://github.com/HiWay-Media/keycloak-fitp-enricher/releases/download/v0.1.1/fitp-enricher-0.1.1.jar /opt/keycloak/providers/fitp-enricher-0.1.1.jar
# build optimized image with all providers in a single pass
RUN ls -l /opt/keycloak/providers/ && /opt/keycloak/bin/kc.sh build
#
FROM quay.io/keycloak/keycloak:22.0.1
WORKDIR /opt/keycloak
COPY --from=builder /opt/keycloak/ /opt/keycloak/
#
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
#
