FROM quay.io/keycloak/keycloak:22.0.1 as builder
#ENV KC_HEALTH_ENABLED=true
ENV KC_FEATURES=token-exchange
ENV KC_METRICS_ENABLED=true
#ENV KC_HTTP_RELATIVE_PATH="/auth"
# Install custom providers
# Apple Social Identity Provider - https://github.com/klausbetz/apple-identity-provider-keycloak
ADD --chown=keycloak:keycloak https://github.com/klausbetz/apple-identity-provider-keycloak/releases/download/1.10.0/apple-identity-provider-1.10.0.jar /opt/keycloak/providers/apple-identity-provider-1.10.0.jar
# build optimized image
RUN /opt/keycloak/bin/kc.sh build 
#
FROM quay.io/keycloak/keycloak:22.0.1 as druid
#ENV KC_HEALTH_ENABLED=true
ENV KC_FEATURES=token-exchange
ENV KC_METRICS_ENABLED=true
# Install custom providers
COPY druid-social-identity-provider-v1.1.0.jar /opt/keycloak/providers/druid-social-identity-provider-v1.1.0.jar
# build optimized image
RUN /opt/keycloak/bin/kc.sh build
#
#
FROM quay.io/keycloak/keycloak:22.0.1
WORKDIR /opt/keycloak
COPY --from=builder /opt/keycloak/ /opt/keycloak/
COPY --from=druid /opt/keycloak/ /opt/keycloak/
RUN ls -l /opt/keycloak/
RUN /opt/keycloak/bin/kc.sh build 
#
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
#
